name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

  deploy:
    runs-on: self-hosted
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write out the kubeconfig info
        run: |
          echo ${{ secrets.DEPLOY_ACCOUNT }} | base64 -d > /tmp/config

      - name: helm deploy
        run: |
          helm repo add influxdata https://helm.influxdata.com/
          helm upgrade --install my-telegraf influxdata/telegraf
        env:
          KUBECONFIG: /tmp/config

      - name: Remove kubeconfig info
        run: rm -f /tmp/config

