name: helm deploy

on: [push]

jobs:
  deploy:
    environment: test
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write out the kubeconfig info
        run: |
          echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 -d > /tmp/config

      - name: helm deploy
        run: |
          helm upgrade --install otel-operator deployment/helm/otel-operator/ -f deployment/helm/otel-operator/values.yaml
        env:
          KUBECONFIG: /tmp/config

      - name: Remove kubeconfig info
        run: rm -f /tmp/config

