name: Clone Wiki to current branch

on:
  push:
    branches:
      - wiki-review

env:
  USER_TOKEN: ${{ secrets.WIKI_ACTION_TOKEN }}
  USER_NAME: nipusa2027
  USER_EMAIL: nipusa2027@outlook.com
  OWNER: ${{ github.event.repository.owner.name }} # This is the repository owner
  REPOSITORY_NAME: ${{ github.event.repository.name }} # This is the repository name

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull content from wiki
        run: |
          mkdir tmp_wiki
          cd tmp_wiki
          git init
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git pull https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git
          ls -ltr ./
    
      - name: Push wiki content to current branch
        run: |
          mkdir wiki
          cp tmp_wiki/* wiki/
          ls -ltr ./
          ls -ltr wiki/
          ls -ltr tmp_wiki/
          git add wiki/
          git commit -m "clone Wiki content"
          git push -f --set-upstream https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.git wiki-review
