name: Clone Wiki to current branch

on:
  push:
    branches:
      - wiki-review

env:
  USER_TOKEN: ${{ secrets.WIKI_ACTION_TOKEN }}
  USER_NAME: nipusa2027
  USER_EMAIL: nipusa2027@outlook.com
  OWNER: ${{ github.event.repository.owner.name }} # This is the repository owner
  REPOSITORY_NAME: ${{ github.event.repository.name }} # This is the repository name

jobs:
  clone_wiki_to_repo:
    name: Clone wiki to repo
    runs-on: ubuntu-latest
    steps:
      - name: clone wiki to current repo
        run: |
          git clone https://github.com/$OWNER/$REPOSITORY_NAME.wiki.git
          cd audit_logging.wiki
          git remote add mirror https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.git
          git pull -v
          git push -u mirror

